name: Pull Request Check

on:
    pull_request:
        branches: [wiki]
    workflow_dispatch:

env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
    build:
        name: Build Check
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Install Node
              uses: actions/setup-node@v3
              with:
                  node-version-file: .nvmrc
                  cache: npm

            - name: Install 🔧
              run: npm ci
            
            - name: Check eslint 🔧
              run: npm run lint

            - name: Build 🔧
              run: npm run build
